include: package:lint/analysis_options_package.yaml

analyzer:
  errors:
    invalid_use_of_protected_member: error
    avoid_relative_lib_imports: error
    avoid_slow_async_io: error
    avoid_types_as_parameter_names: error
    cancel_subscriptions: error
    close_sinks: error
    valid_regexps: error
    always_require_non_null_named_parameters: error

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: false
    use_setters_to_change_properties: false
    prefer_double_quotes: true
    avoid_classes_with_only_static_members: false
