name: sample
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auth:
    path: features/auth
  bolter_flutter: 5.1.1
  cupertino_icons: ^1.0.2
  cupertino_list_tile: 0.2.0
  isolated_http_client: 1.4.3
  flutter:
    sdk: flutter
  image_picker: 0.7.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_annotation: ^4.0.1
  json_serializable: ^4.1.3
  lint: 1.5.3

flutter:
  assets:
    - assets/images/
