name: auth
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  isolated_http_client: ^1.4.3

dev_dependencies:
  build_runner: ^2.0.4
  lint: ^1.5.3
  json_annotation: ^4.0.1
  json_serializable: ^4.1.3
  test: ^1.17.5
